FROM ludotech/python3.9-poetry

MAINTAINER  shiyangzhang

WORKDIR /user/local/workspace
COPY . .
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt 
EXPOSE 5000
CMD echo "---end-------" 




